apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-config
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  # Drachtio connection
  DRACHTIO_HOST: {{ .Values.drachtioHost | quote }}
  DRACHTIO_PORT: {{ .Values.drachtioPort | quote }}
  DRACHTIO_SIP_PORT: {{ .Values.drachtioSipPort | quote }}
  
  # SIP outbound configuration (public settings)
  SIP_OUTBOUND_PROVIDER: {{ .Values.sipOutbound.provider | quote }}
  SIP_OUTBOUND_DOMAIN: {{ .Values.sipOutbound.domain | quote }}
  SIP_OUTBOUND_USERNAME: {{ .Values.sipOutbound.username | quote }}
  SIP_OUTBOUND_PORT: {{ .Values.sipOutbound.port | quote }}
  {{- if .Values.sipOutbound.proxy }}
  SIP_OUTBOUND_PROXY: {{ .Values.sipOutbound.proxy | quote }}
  {{- end }}
  
  # SIP inbound configuration
  SIP_INBOUND_ENABLED: {{ .Values.sipInbound.enabled | quote }}
  SIP_INBOUND_PORT: {{ .Values.sipInbound.port | quote }}
  
  # RTP configuration
  RTP_PORT_MIN: {{ .Values.rtpPortMin | quote }}
  RTP_PORT_MAX: {{ .Values.rtpPortMax | quote }}
  JITTER_BUFFER_MS: {{ .Values.rtpJitterBufferMs | quote }}
  
  # Recording configuration
  CALL_RECORDING_ENABLED: {{ .Values.recordingEnabled | quote }}
  CALL_RECORDINGS_PATH: {{ .Values.recordingPath | quote }}
  
  # Transcription configuration
  TRANSCRIPTION_ENABLED: {{ .Values.transcriptionEnabled | quote }}
  TRANSCRIPTION_MODEL: {{ .Values.transcriptionModel | quote }}
  TRANSCRIPTION_DISPLAY_TO_CONSOLE: {{ .Values.transcriptionDisplayToConsole | quote }}
  
  # Audio configuration
  TEST_AUDIO_TEMPO: {{ .Values.audioTestTempo | quote }}
  AI_AUDIO_TEMPO: {{ .Values.audioAiTempo | quote }}
  
  # Network configuration
  LOCAL_IP: {{ .Values.localIp | quote }}
  
  # OpenAI configuration (public settings)
  OPENAI_ENABLED: {{ .Values.openaiEnabled | quote }}
  
  # Generic environment variables
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}