apiVersion: v1
kind: Service
metadata:
  name: drachtio
  labels:
    app: drachtio
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  clusterIP: {{ .Values.drachtioServiceClusterIP }}  # Headless service for StatefulSet
  selector:
    app: drachtio
  ports:
  - name: control
    port: {{ .Values.drachtioPort }}
    targetPort: {{ .Values.drachtioPort }}
    protocol: TCP
  - name: sip-udp
    port: {{ .Values.drachtioSipPort }}
    targetPort: {{ .Values.drachtioSipPort }}
    protocol: UDP
  - name: sip-tcp
    port: {{ .Values.drachtioSipPort }}
    targetPort: {{ .Values.drachtioSipPort }}
    protocol: TCP