apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drachtio
  labels:
    app: drachtio
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  serviceName: drachtio
  replicas: 1
  selector:
    matchLabels:
      app: drachtio
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: drachtio
        {{- range $key, $value := .Values.globalLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: drachtio
        image: {{ .Values.drachtioImageRepository }}:{{ .Values.drachtioImageTag }}
        imagePullPolicy: {{ .Values.drachtioImagePullPolicy }}
        command:
        - drachtio
        - --file
        - /etc/drachtio/drachtio.conf.xml
        volumeMounts:
        - name: drachtio-secret
          mountPath: /etc/drachtio
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.drachtioResourcesMemoryRequests | quote }}
            cpu: {{ .Values.drachtioResourcesCpuRequests | quote }}
          limits:
            memory: {{ .Values.drachtioResourcesMemoryLimits | quote }}
            cpu: {{ .Values.drachtioResourcesCpuLimits | quote }}
      volumes:
      - name: drachtio-secret
        secret:
          secretName: drachtio-secret