apiVersion: v1
kind: Secret
metadata:
  name: drachtio-secret
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
stringData:
  drachtio.conf.xml: |
    <drachtio>
        <!-- admin connection configuration -->
        <admin port="9022" secret="{{ .Values.drachtioSecret }}">0.0.0.0</admin>
      
        <!-- sip configuration -->
        <sip>
            <!-- bind to all interfaces on port 5060 for UDP transport -->
            <contacts>
                <contact>sip:*:5060;transport=udp</contact>
            </contacts>

            <!-- spam protection -->
            <spammers action="reject" tcp-action="discard">
                <header name="User-Agent">
                    <value>sip-cli</value>
                    <value>sipcli</value>
                    <value>friendly-scanner</value>
                </header>
                <header>
                    <value>sipvicious</value>
                </header>
            </spammers>
        </sip>

        <!-- call detail records -->
        <cdrs>true</cdrs>
                
        <!-- logging configuration -->
        <logging>
            <console/>
            <sofia-loglevel>3</sofia-loglevel>
            <loglevel>{{ .Values.drachtioLogLevel }}</loglevel>
        </logging>
            
    </drachtio>