apiVersion: v1
kind: Service
metadata:
  name: drachtio
  labels:
    app: drachtio
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: drachtio
  ports:
  - name: control
    port: 9022
    targetPort: 9022
    protocol: TCP
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    targetPort: 5060
    protocol: TCP