apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
stringData:
  secrets.yaml: |
    drachtio:
      secret: {{ .Values.drachtioSecret | quote }}

    mediaServer:
      secret: {{ .Values.mediaServerSecret | quote }}

    openai:
      apiKey: {{ .Values.openaiApiKey | quote }}

    sip:
      outbound:
        password: {{ .Values.sipOutbound.password | quote }}