apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  labels:
    app: firefly
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
        {{- range $key, $value := .Values.globalLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: firefly
        image: {{ .Values.fireflyImageRepository }}:{{ .Values.fireflyImageTag }}
        imagePullPolicy: {{ .Values.fireflyImagePullPolicy }}
        command: ["node", "dist/index.js"]
        args:
          - --config
          - /var/run/firefly-config/config.yaml
          - --config
          - /var/run/firefly-secrets/secrets.yaml
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /var/run/firefly-config
          readOnly: true
        - name: secrets
          mountPath: /var/run/firefly-secrets
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.fireflyResourcesMemoryRequests | quote }}
            cpu: {{ .Values.fireflyResourcesCpuRequests | quote }}
          limits:
            memory: {{ .Values.fireflyResourcesMemoryLimits | quote }}
            cpu: {{ .Values.fireflyResourcesCpuLimits | quote }}
        # Health checks - TCP probe for drachtio connection
        livenessProbe:
          tcpSocket:
            port: 9022
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9022
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: config
        configMap:
          name: firefly-config
      - name: secrets
        secret:
          secretName: firefly-secrets