apiVersion: v1
kind: Secret
metadata:
  name: freeswitch-secret
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
stringData:
  password: "{{ .Values.freeswitchSecret }}"