{{- if .Values.persistenceEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-recordings
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistenceAccessMode }}
  {{- if .Values.persistenceStorageClass }}
  storageClassName: {{ .Values.persistenceStorageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistenceSize }}
{{- end }}