apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
  labels:
    {{- range $key, $value := .Values.globalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
  {{- end }}
  {{- if .Values.drachtioSecret }}
  DRACHTIO_SECRET: {{ .Values.drachtioSecret | b64enc }}
  {{- end }}
  {{- if .Values.sipOutbound.password }}
  SIP_OUTBOUND_PASSWORD: {{ .Values.sipOutbound.password | b64enc }}
  {{- end }}