# Default values for firefly Helm chart
# This file contains public configuration values
# For secrets, use values.local.yaml (gitignored)

# Global settings
globalLabels:
  app.kubernetes.io/name: firefly
  app.kubernetes.io/version: latest

# Drachtio SIP server configuration
drachtioImageRepository: drachtio/drachtio-server
drachtioImageTag: "0.9.3"
drachtioImagePullPolicy: IfNotPresent
drachtioHost: localhost
drachtioSecret: ""  # Set in values.local.yaml
drachtioLogLevel: info


# Drachtio resource limits
drachtioResourcesMemoryRequests: "128Mi"
drachtioResourcesCpuRequests: "100m"
drachtioResourcesMemoryLimits: "256Mi"
drachtioResourcesCpuLimits: "200m"

# FreeSWITCH media server configuration
freeswitchEnabled: true
freeswitchImageRepository: ai-voicechat-playground/freeswitch
freeswitchImageTag: "0.9.4"
freeswitchImagePullPolicy: IfNotPresent
freeswitchEventSocketPort: 8021
freeswitchSecret: ""  # Set in values.local.yaml

# FreeSWITCH resource limits
freeswitchResourcesRequestsMemory: "128Mi"
freeswitchResourcesRequestsCpu: "100m"
freeswitchResourcesLimitsMemory: "512Mi"
freeswitchResourcesLimitsCpu: "500m"

# Firefly application configuration
fireflyImageRepository: firefly
fireflyImageTag: latest
fireflyImagePullPolicy: IfNotPresent

# Firefly resource limits
fireflyResourcesMemoryRequests: "256Mi"
fireflyResourcesCpuRequests: "250m"
fireflyResourcesMemoryLimits: "512Mi"
fireflyResourcesCpuLimits: "500m"


# SIP outbound registration configuration
sipOutbound:
  provider: disabled  # Options: disabled, kyivstar
  domain: ""
  username: ""
  port: 5060
  password: ""  # Set in values.local.yaml
  proxy: ""

# SIP inbound registration configuration (accepts registrations from SIP clients)
sipInbound:
  enabled: true
  port: 5062


# Call recording configuration
recordingEnabled: true

# Persistent volume for recordings
persistenceStorageClass: ""
persistenceAccessMode: ReadWriteOnce
persistenceSize: 5Gi

# Transcription configuration
transcriptionEnabled: true
transcriptionDisplayToConsole: true

# Audio configuration
audioTestTempo: 1.0
audioAiTempo: 1.0

# Network configuration
# localIp: automatically set by Tiltfile to minikube ip

# OpenAI configuration
openaiEnabled: false  # Must be explicitly enabled
openaiApiKey: ""  # Set in values.local.yaml

# Routing configuration
defaultRoute: welcome  # Options: echo, chat, welcome
ringDelayMs: 3000  # Ring delay in milliseconds (0-30000) for natural interaction

# Media server configuration
mediaServerAddress: "127.0.0.1"
mediaServerPort: 8021
mediaServerSecret: ""  # Set in values.local.yaml
mediaServerEnabled: true

# Welcome audio configuration
welcomeAudioPath: "audio/welcome.aiff"  # Relative to firefly directory
welcomeAudioFallbackToTone: true



# Configuration values for template generation
environment: development